import type { Metadata } from "next";
import { Mulish, Bitcount, Saira } from "next/font/google";
import "./globals.css";

const bitCount = Bitcount({
  variable: "--font-bitcount",
  subsets: ["latin"],
});

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
});


const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "gaurav_abhiman_mahajan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bitCount.variable} ${saira.variable} ${mulish.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
